### ISSUE TITLE
Update pathogen-repo-ci to "generic"/"smart" workflow

### ISSUE THREAD

**Issue by genehack** [nextstrain/.github#89]
### Context
Per [recent discussion](https://docs.google.com/document/d/1cdIwko_izJl5xuc1k54GDkP0Wt40eo6gFIkS5XQhCM4/edit), as well as various legacy conversations [here](https://github.com/nextstrain/pathogen-repo-guide/issues/25), [here](https://docs.google.com/document/d/1moFrcYo_gqQ8AT5tGHTpP0PwG-zMUaRIsERGcccRw-0/edit#heading=h.2o0ioyug4vc9), and [here](https://github.com/nextstrain/pathogen-repo-guide/issues/21), we want to update the `pathogen-repo-ci` GitHub Action to a "strict" version that can be used across all of our "modern" pathogen repos with zero configuration on the consuming repo side. 

### Description
Update the `pathogen-repo-ci` workflow so that:

1. _If_ the top-level `nextstrain-pathogen.yaml` file is present
2. For each build-name (i.e., each of `ingest`, `phylogenetic`, and `nextclade`):
    a. _If_ the repo contains a `<build-name>/Snakefile` file and a `<build-name>/build-configs/ci/config.yaml` file
    b. Run `nextstrain build <build-name>  --configfile build-configs/ci/config.yaml`

The consuming repo will be responsible for providing an appropriate config file that either sets up appropriate example data or results in a subset of a full workflow being run, so as to validate that the repo workflows have not been broken by a change. 

### Examples

This workflow, plus the appropriate build-config files, should be sufficient to enable CI for a pathogen repo:

```
name: CI
on:
  - push
  - workflow_dispatch
jobs:
  ci:
    name: CI
    uses: nextstrain/.github/workflows/pathogen-repo-ci.yaml
```

**Comment by joverlee521** [comment]
100% support this direction. 

One additional check I would add to the `pathogen-repo-ci` is the presence of the top level `nextstrain-pathogen.yaml` file within the pathogen repo. This ensures `nextstrain build` is able to access of files between subdirectories, e.g. both `phylogenetic` might need to access files from the top level `shared` directory. ([nextstrain-cli v8.2.0 release notes](https://github.com/nextstrain/cli/releases/tag/8.2.0) has more details.)

**Comment by tsibley** [comment]
+1 from me.

For the calling workflow in each repo, I'd extend the default set of triggers, e.g. something like

```yaml
on:
  push:
    branches:
      - main # or "master", as required
  pull_request:
  workflow_dispatch:

  # Routinely check that we continue to work in the face of external changes.
  schedule:
    # Every day at 17:42 UTC / 9:42 Seattle (winter) / 10:42 Seattle (summer)
    - cron: "42 17 * * *"
```

c.f. https://github.com/nextstrain/.github/blob/5ab8d7aa3c97ca3257dfa9fc201f1463034f3e6d/workflow-templates/pathogen-repo-ci.yaml as well
